version: '3.9'

services:

  database:
    image: postgres:15.1
    #restart: unless-stopped
    container_name: flask_db
    env_file: .env
    volumes:
      - flask_db:/var/lib/postgresql/data/
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - flask

volumes:
  flask_db:

networks:
  flask: