# example from chemotion:


# version: '3.5'
# services:
#     db:
#         image: postgres:13
#         restart: unless-stopped
#         hostname: db
#         environment:
#             - POSTGRES_USER=postgres
#             - POSTGRES_PASSWORD=postgres
#         volumes:
#             - chemotion_db:/var/lib/postgresql/data/
#         networks:
#             - chemotion

#     msconvert:
#         image: ptrxyz/chemotion:msconvert-1.3.1p220712
#         restart: unless-stopped
#         hostname: msconvert
#         volumes:
#             - spectra:/shared:rw
#         networks:
#             - chemotion

#     spectra:
#         image: ptrxyz/chemotion:spectra-1.3.1p220712
#         restart: unless-stopped
#         hostname: spectra
#         volumes:
#             - spectra:/shared:rw
#         depends_on:
#             - msconvert
#         networks:
#             - chemotion

#     worker:
#         image: ptrxyz/chemotion:eln-1.3.1p220712
#         restart: unless-stopped
#         environment:
#             - CONFIG_ROLE=worker
#         depends_on:
#             - db
#             - eln
#             - spectra
#         volumes:
#             - chemotion_data:/chemotion/data/
#             - chemotion:/chemotion/app
#         networks:
#             - chemotion

#     eln:
#         image: ptrxyz/chemotion:eln-1.3.1p220712
#         restart: unless-stopped
#         environment:
#             - CONFIG_ROLE=eln
#         depends_on:
#             - db
#             - spectra
#         volumes:
#             - ./shared/pullin:/shared
#             - ./shared/backup:/backup
#             - chemotion_data:/chemotion/data/
#             - chemotion:/chemotion/app
#         ports:
#             - 4000:4000
#         networks:
#             - chemotion

# volumes:
#     chemotion:
#         name: chemotion_app
#     chemotion_data:
#         name: chemotion_data
#     chemotion_db:
#         name: chemotion_db
#     spectra:

# networks:
#     chemotion:


###################################

# other examples:

#version: "3.9"
#
#services:
#  db:
#    image: postgres
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#  web:
#    build: .
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/code
#    ports:
#      - "8000:8000"
#    environment:
#      - POSTGRES_NAME=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    depends_on:
#      - db

###############

#version: '3.5'
#
#services:
#
#  nginx:
#    container_name: nginx_server
#    image: nginx:latest
#    depends_on:
#      - django
#    ports:
#      - "0.0.0.0:81:80"
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./django/mysite/mysite/static:/var/www/djangoapp/static
#    networks:
#      - postgres
#    restart: unless-stopped
#
#  django:
#    container_name: django
#    build: ./django
#    depends_on:
#      - postgres
#    ports:
#      - "8002:8002"
#    volumes:
#       - ./django/mysite:/app
#    networks:
#      - postgres
#    restart: unless-stopped
#    tty: true
#
#  postgres:
#    container_name: postgres_container
#    build: ./postgres
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER:-postgres}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
#      PGDATA: /data/postgres
#    volumes:
#       - postgres:/data/postgres
#    ports:
#      - "5432:5432"
#    networks:
#      - postgres
#    restart: unless-stopped
#
#networks:
#  postgres:
#    driver: bridge
#
#volumes:
#    postgres:
#    pgadmin: