version: '3.9'

services:

  database:
    image: postgres:15.1
    #restart: unless-stopped
    container_name: flask_db
    env_file: .env
    volumes:
      - flask_db:/var/lib/postgresql/data/
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - flask

  backend:
    container_name: flask_backend
    #restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - POSTGRES_HOST=database
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - flask
    depends_on:
      - database

volumes:
  flask_db:

networks:
  flask: