version: '3.9'

services:

  database:
    container_name: eln_db
    # restart: unless-stopped
    image: postgres:15.1
    env_file: .env
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    volumes:
      - eln_db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - eln

  frontend:
    container_name: eln_frontend
    # restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
#    ports:
#      - "3000:3000"
#    depends_on:
#      - backend
    volumes:
      - build:/app/build
      # - ./frontend:/app
#    stdin_open: true
#    tty: true
#    networks:
#      - eln

  backend:
    container_name: eln_backend
    # restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - ./backend:/app
      - static:/app/static
      - media:/app/media
    networks:
      - eln

  nginx:
    container_name: nginx
    image: nginx:1.23-alpine
    # restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      # - ./certbot/conf:/etc/nginx/ssl
      # - ./certbot/data:/usr/share/nginx/html/letsencrypt
      - build:/var/www/frontend
      - static:/static
      - media:/media
    depends_on:
      - database
      - backend
      - frontend
    networks:
      - eln

#  certbot:
#    container_name: certbot
#    image: certbot/certbot:latest
#    restart: unless-stopped
#    # command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email email@email.com --agree-tos --no-eff-email -d domain.com
#    volumes:
#      - ./certbot/conf:/etc/letsencrypt
#      - ./certbot/data:/usr/share/nginx/html/letsencrypt
#      - ./certbot/logs:/var/log/letsencrypt
#    networks:
#      - flask_eln

volumes:
  eln_db:
  build:
  static:
  media:

networks:
  eln:
    name: flask_eln