version: '3.9'

services:

  database:
    image: postgres:15.1
    #restart: unless-stopped
    container_name: eln_db
    env_file: .env
    volumes:
      - eln_db:/var/lib/postgresql/data/
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - eln

  backend:
    container_name: eln_backend
    #restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - POSTGRES_HOST=database
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - eln
    depends_on:
      - database

volumes:
  eln_db:

networks:
  eln: